### ISSUE TITLE
User permissions are not obeyed

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#23]
Here is how to reproduce the issue:
- create a user, assign to that user the "Project Administrator" role in some projects, but not in others;
- go to Administration/Search and use the following search expression: `find configuration with project id _Root`.
Expected: only build configurations where the user has some permissions will be displayed;
Actual: all build configurations in all projects will be displayed.

**Comment by ilyavoronin** [comment]
security context is now passed in new thread in SearchAdminPage
