### ISSUE TITLE
"enabled" filter seems to be supported but does not work for project features

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#32]
In fact unlike the case with build features, there is no generic mechanism for disabling project features. So if a project feature allows disabling it implements its own mechanism. For example `versionedSettings` project feature sets its parameter `enabled` to `false`. 

Yet we do seemingly support `enabled` filter for project feature, but it does nothing. It should be either not supported or at least take into account the value of the `enabled` parameter. There is something to discuss here.

**Comment by ilyavoronin** [comment]
Moved to youtrack: [TW-69429](https://youtrack.jetbrains.com/issue/TW-69429)
