### ISSUE TITLE
Setting types may be difficult to understand for users

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#34]
Some build step types like "Ant" or "Maven2" are self-explanatory, but there others, e.g. "JPS" that may not be obvious for users. 
The same applies to the names and some values of parameters of various settings.

As for the setting types, it could be resolved to an extent if we manage to support showing additional information in the auto-completion popup. We could extract the display names via the respective getDisplayName() calls, e.g. via 

`buildFeatureDescriptor.getBuildFeature().getDisplayName()`

(the code needs a null check though)

It is unlikely that we could resolve the similar issue for parameter names and values within the plugin, as human readable names are not possible to obtain via API.

**Comment by ilyavoronin** [comment]
Add names from the ui for build steps and trigger types
