### ISSUE TITLE
Always use a sub-string search in the `val` filter

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#35]
The `val` filter searches any values within some scope. Currently it employs equality comparison by default, and if a user wants to find values that contain a certain substring, she must use `*substring*` syntax. It seems such an approach makes no sense, as one of the main use cases for this filter is a search of parameter references.

**Comment by ilyavoronin** [comment]
Moved to youtrack: [TW-69426](https://youtrack.jetbrains.com/issue/TW-69426)
