### ISSUE TITLE
Don't force % sign to be surrounded with double quotes in values

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#36]
As  the % sign is used in defining parameter references, it should be quite easy to use such values in filters. So instead of `*"%param%"*` (or `"*%param%*"`) it should be possible to say just`*%param%*`.

**Comment by ilyavoronin** [comment]
Moved to youtrack: [TW-69428](https://youtrack.jetbrains.com/issue/TW-69428)
