### ISSUE TITLE
Double-quoting inside of a wildcard expression looks unnatural

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#37]
E.g. "anything containing the name John Doe" is currently expressed as `*"Jane Doe"*`, which is not very obvious syntax.

I suggest to change that and allow to include wildcards inside the double quoted strings, e.g. `"*Jane Doe*"`

**Comment by ilyavoronin** [comment]
Moved to youtrack: [TW-69427](https://youtrack.jetbrains.com/issue/TW-69427)
