### ISSUE TITLE
`enabled` filter must allow for true/false values

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#38]
Currently there is an `enabled` filter that can be applied to build configuration and template settings. The result will then only include entities where the corresponding setting was enabled, as against to these where it is either enabled or disabled. 

It makes it impossible to find only those entities where a setting is disabled.

So it is suggested to replace `enabled` with `enabled = true` and `enabled = false`.

**Comment by ilyavoronin** [comment]
Moved to youtrack: [TW-69425](https://youtrack.jetbrains.com/issue/TW-69425)
