### ISSUE TITLE
When the query does not satisfy the grammar, the error message could be misleading

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#39]
E.g. the query `find project with`, which is missing the condition completely results in the following error:

**Wrong query: mismatched input '' expecting {'(', 'not', PROJECT, TEMPLATE, VCS_ROOT, ID, PARENT, TRIGGER, STEP, FEATURE, TYPE, PARAM, VAL, ENABLED, ANCESTOR, RULES, DEPENDENCY, ARTIFACT, SNAPSHOT, OPTION, CLEAN, REV_RULE, VCS_ENTRY, NAME} at position 18**

First of all it lists not the keywords, but some internal token names.
It also includes more of these than are actually allowed at that point. E.g. there are neither steps nor dependencies in project and you cannot filter project directly using these filters.

**Comment by ilyavoronin** [comment]
Moved to youtrack: [TW-69424](https://youtrack.jetbrains.com/issue/TW-69424)
