### ISSUE TITLE
The "?" style auto-completion does not wrap values in double quotes where they must be wrapped

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#40]
Here is how to reproduce:

- in some project create a parameter `somename` with a value `Jane Doe`;
- in the Search QL string type `find project with param somename = ?`
- `Jane Doe` will be suggested, but if you pick it and run the query `find project with param somename = Jane Doe`, it will fail.

Expected behavior (two options): 
- either a suggestion itself must be double-quoted as in `"Jane Doe"`;
- or the suggestion may not be duble-quoted, but if selected, the resulting value must be double-quoted, as in  `find project with param somename = "Jane Doe"`

**Comment by ilyavoronin** [comment]
suggested value is wrapped in double quotes
