### ISSUE TITLE
Search results: add "more results" button

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#43]
Currently we limit the number of search results to 100. It would be nice if we could allow users to show more results if they wish so. A button "More..." or some kind of pagination, possibly. It has to be discussed first.

As a first step though, it would be nice to have at least some indication at the end of the page that these are not all results. And possibly total number of results should be displayed if it makes sense computationally.

**Comment by ilyavoronin** [comment]
"Show more" button added
