### ISSUE TITLE
Add support for meta-runner keyword

### ISSUE THREAD

**Issue by ogerovich** [JetBrains/teamcity-search-ql#49]
For example:
```
find meta-runner with step type python
```

**Comment by ilyavoronin** [comment]
added meta-runner queries. examples:
```
find metaRunner with parent (not archived) and step (type simpleRunner)
```
will find all meta-runners in non-archived projects which use step with type "simpleRunner".

```
find configuration,metaRunner with step type simpleRunner
```
will find all meta-runners and build configurations which use step with type "simpleRunner"

Autocompletion is not implemented for strings inside meta-runners subfilters(name, id, param). But context-autocompletion with '?' still works:
```
find metaRunner with parent (not archived) and param ?
```
will suggest all possible parameter names for metaRunners inside non-archived projects
