### ISSUE TITLE
Add tempate, configuration, vcsRoot, subProject(?) filters to projects

### ISSUE THREAD

**Issue by karanagai** [JetBrains/teamcity-search-ql#5]
Currently we cannot filter projects based by their subordinate entities (sub-projects, build configurations, templates, VCS roots). It is worth considering implementing these filters.

There is an open question though: should we consider transitive relationships, i.e. if P1 contains P2 that contains P3, should we return just P2 or both P1 and P2 while filtering by P3?

**Comment by karanagai** [comment]
It seems we don't have to consider transitive relationships by default, but possibly it should be a modifier [transitive] that could be applied here

**Comment by ilyavoronin** [comment]
add template, configuration and subProject filters for project
